### ISSUE TITLE
Doesn't work in a Modal

### ISSUE THREAD

**Issue by pavlov01** [Dani3lSun/apex-plugin-spotlight#3]
Hi.
I'm using this fantastic plugin and it makes me think about fancy features I can implement on my site.
But I'm having an issue: Using it in a modal doesn't work. If you iplement it in a page it works, than make that page a modal and the search box doesn't open.

Not precisely: I succeded in opening it over my modal, but I needed a hidden button in the opening page. when the modal opens and I start typing in my search field, the evnt triggers the click event on the opener making the spotlight box appear. It makes its job, but when I choose my result, the launched js doesn't have any visibility of the elements in the modal. I needed to put a js (the one I use to give back my result from the list) in the opener. It works. I succeded in reaching my elements in the modal, but no events can be triggered and any Jquery selector simply don't work.
I succeded in reaching my elements fron the opening page with:
<pre>parent.frames[0].document.getElementsByName("myFieldID")[0]</pre>

It's far from elegant and it doesn't allow me to do what I'm thinking about....

Any suggestion?
Many Thanks

**Comment by Dani3lSun** [comment]
Hi @pavlov01 

yeah I know that it doesn't work in modal dialogs, thus it is intended behavior, see this line in the source code:
https://github.com/Dani3lSun/apex-plugin-spotlight/blob/51059188b48a236545da53433eac2933fa90ba35/src/files/js/apexspotlight.js#L884

Thus Spotlight Search itself is a modal dialog, there can be some strange issues when it is opened inside of modals, like flickering dialogs, resizing issues and so on...
The original spotlight search in the APEX builder (since APEX 18.1) has the same limitation, it only works on normal pages...
